[site]
title = "Tao Xu"
description = "Undergraduate student at Sichuan University."
favicon = "/favicon.png"
last_updated = "May 25, 2026"

[author]
name = "Tao Xu"
title = "Undergraduate"
institution = "Sichuan University"
avatar = "/bio.jpg"

[social]
# Contact information (leave blank or delete to hide)

email = "summer_xt17@163.com"
location = "Chengdu, China"
location_url = "https://www.google.com/maps/place/Sichuan+University+Jiang'an+Campus+%EF%BC%88North+Gate%EF%BC%89/@30.5628145,103.9918239,17z/data=!4m6!3m5!1s0x36efc13bad07ff69:0xe4ab49017832f663!8m2!3d30.562213!4d103.992544!16s%2Fg%2F11cm1lgcz8?entry=ttu&g_ep=EgoyMDI2MDIxOC4wIKXMDSoASAFQAw%3D%3D"
location_details = [
  "No. 2, Chuanda Road, Science Building,",
  "Shuangliu District, Chengdu, China"
]
google_scholar = "https://scholar.google.com/citations?user=cnf2xiQAAAAJ&hl=en"
orcid = "https://orcid.org/my-orcid?orcid=0009-0009-2462-9819"
github = "https://github.com/L77Doncic"

[features]
# Show a like button on the about page
enable_likes = false

# Display all subpages on a single page
enable_one_page_mode = false

[i18n]
enabled = true
locales = ["zh", "en"]
default_locale = "en"
# "auto" means the locale will be determined by the browser's language setting, "fixed" means the locale will be fixed to the default locale (but can be switched still, if you want to disable, set "enable=false")
mode = "auto"
fixed_locale = "en"
# If true, PRISM will remember user's language preference in browser's localStorage
persist = true
# Show a language switcher on the top right corner
switcher = true

[i18n.labels]
zh = "中文"
en = "English"

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "Awards"
type = "page"
target = "awards"
href = "/awards"

[[navigation]]
title = "Services"
type = "page"
target = "services"
href = "/services"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"
