[[news]]
date = "2026-5"
content = "We received Provincial 2nd Prize in the 19th China Collegiate Computer Design Competition, which still feels a bit regretful 😮‍💨"

[[news]]
date = "2026-5"
content = "We received Honorable Mention in MCM/ICM 😮‍💨"

[[news]]
date = "2026-4"
content = "We won National 3rd Prize in the Huawei ICT Competition 🎉"

[[news]]
date = "2026-3"
content = "Our work has been accepted by KSEM2026 🎉"
