[site]
title = "许涛"
description = "四川大学本科生。"
last_updated = "2026年5月25日"

[author]
name = "许涛"
title = "本科生"
institution = "四川大学"
avatar = "/bio.jpg"

[social]
email = "summer_xt17@163.com"
location = "成都，中国"
location_url = "https://www.google.com/maps/place/Sichuan+University+Jiang'an+Campus+%EF%BC%88North+Gate%EF%BC%89/@30.5628145,103.9918239,17z/data=!4m6!3m5!1s0x36efc13bad07ff69:0xe4ab49017832f663!8m2!3d30.562213!4d103.992544!16s%2Fg%2F11cm1lgcz8?entry=ttu&g_ep=EgoyMDI2MDIxOC4wIKXMDSoASAFQAw%3D%3D"
location_details = [
  "川大路2号，",
  "双流区，成都，中国"
]
google_scholar = "https://scholar.google.com/citations?user=cnf2xiQAAAAJ&hl=en"
orcid = "https://orcid.org/my-orcid?orcid=0009-0009-2462-9819"
github = "https://github.com/L77Doncic"

[[navigation]]
title = "关于我"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "论文"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "奖项"
type = "page"
target = "awards"
href = "/awards"

[[navigation]]
title = "服务"
type = "page"
target = "services"
href = "/services"

[[navigation]]
title = "简历"
type = "page"
target = "cv"
href = "/cv"
