[[news]]
date = "2026-5"
content = "我们获得第十九届中国大学生计算机设计大赛省级二等奖，有点可惜 😮‍💨"

[[news]]
date = "2026-5"
content = "我们获得美国大学生数学建模竞赛（MCM/ICM）H奖 😮‍💨"

[[news]]
date = "2026-4"
content = "我们获得华为ICT大赛全国三等奖 🎉"

[[news]]
date = "2026-3"
content = "我们的工作被 KSEM2026 接收了 🎉"
